### ISSUE TITLE
linux下后台运行jar包报错

### ISSUE THREAD

**Issue by dui7** [meteorOSS/wechat-bc#27]
![image](https://github.com/meteorOSS/wechat-bc/assets/18512761/9a51d188-c815-48c4-9b7b-b211f50f809e)
我想问下如何后台运行该程序

**Comment by meteorOSS** [comment]
docker可以在后台挂起应用

安装好docker后进入一个文件夹，创建 `Dockerfile` 文件
```
FROM openjdk:8-jdk-alpine

WORKDIR /app

COPY target/WeChatBc-1.0.6-SNAPSHOT.jar /app/WeChatBc-1.0.6-SNAPSHOT.jar
COPY plugins /app/plugins
CMD ["java", "-jar", "WeChatBc-1.0.6-SNAPSHOT.jar"]
```

同级目录下创建一个"target"文件夹放入jar，还有一个"plugins"放置插件

然后使用 `docker build -t wechatbc .`

构建完成之后输入

`docker run -it --name wx wechatbc` 运行

在控制台按下ctrl+p + q即可挂起，后面输入 `docker attack wx` 即可重新进入控制台
