### ISSUE TITLE
到底怎么发群消息，大佬能给个示例出来吗

### ISSUE THREAD

**Issue by meteorOSS** [meteorOSS/wechat-bc#29]
到底怎么发群消息，大佬能给个示例出来吗

_Originally posted by @lovecodeyou in https://github.com/meteorOSS/wechat-bc/issues/22#issuecomment-1985212580_

**Comment by lovecodeyou** [comment]
并没有作用，还是获取不到群相关的信息

hutool的代码
`CollUtil.getFieldValues(((HashMap)BeanUtil.getProperty(weChatClient.getContactManager(), "contactMap")).values, "nickName")`


![image](https://github.com/meteorOSS/wechat-bc/assets/38997988/5ffc19bb-d587-48a9-91df-8084c6dc12f7)

![image](https://github.com/meteorOSS/wechat-bc/assets/38997988/351ebace-4d47-4658-a24b-524c318658e7)

**Comment by lovecodeyou** [comment]
发现了怎么才能获取到群， 要将群先 【保存到通讯录】才行    ，我干，那么坑爹的吗


![image](https://github.com/meteorOSS/wechat-bc/assets/38997988/cae1582d-0e86-4ba6-acce-3e251db649fd)

**Comment by lovecodeyou** [comment]
如果是未保存到通讯录的群，我这边接收到该群的消息，我这边如何完成相关业务，然后发送群消息呢？

**Comment by meteorOSS** [comment]
> 如果是未保存到通讯录的群，我这边接收到该群的消息，我这边如何完成相关业务，然后发送群消息呢？

你至少要收到一次消息（监听ReceiveMessageEvent），把username存下来
但是username不是固定的，可能会有变化，你可以尝试维护一个缓存。最好还是只在监听器里发送消息至未保存到通讯录的群

**Comment by lovecodeyou** [comment]
群主稳，确实可行

**Comment by lovecodeyou** [comment]
![image](https://github.com/meteorOSS/wechat-bc/assets/38997988/6a2fc40f-229d-4791-baa0-1a8d1b9fda2c)

**Comment by lovecodeyou** [comment]
![image](https://github.com/meteorOSS/wechat-bc/assets/38997988/e87e8572-9b11-4522-a67c-ed0bbdcda230)

**Comment by lovecodeyou** [comment]
还有个疑问，这个消息对象，不能获取到 未保存到通讯录的群名吗？

**Comment by meteorOSS** [comment]
> 还有个疑问，这个消息对象，不能获取到 未保存到通讯录的群名吗？

嗯，是的。
我试试看设置后通过备注获取可不可行，需要一点时间

**Comment by lovecodeyou** [comment]
> > 还有个疑问，这个消息对象，不能获取到 未保存到通讯录的群名吗？
> 
> 嗯，是的。 我试试看设置后通过备注获取可不可行，需要一点时间

麻烦群主了，搞定了@一下我

**Comment by meteorOSS** [comment]
看你的截图，你是直接在wechatbc里做修改吗? 最好用插件扩展
不然之后同步仓库代码的时候，可能会有很多冲突要解决

**Comment by lovecodeyou** [comment]
> 看你的截图，你是直接在wechatbc里做修改吗? 最好用插件扩展 不然之后同步仓库代码的时候，可能会有很多冲突要解决

对的，这不是还在测你这机器人的能力边界吗，等你满足我这边项目改造需求我在单独开个项目以bc插件的形式引入
